/**
 * typy pro třívrstvou importní architekturu.
 * vrstva 1: surová data (beze změny)
 * vrstva 2: návrhy parseru (více bloků)
 * vrstva 3: šablona (autorita uživatele)
 */

// ============ typy bloků ============

export type BlockType = 'kv' | 'table' | 'series' | 'stats' | 'unknown'

export interface DetectedBlock {
    id: string
    type: BlockType
    startRow: number
    endRow: number
    columnCount?: number
    confidence: number // 0:1
    description: string
    headers?: string[]
    sampleRows?: string[][]
    selected?: boolean // uživatel vybral tento blok
    action?: BlockAction // co s tímto blokem udělat
    horizontalSeries?: HorizontalSeriesInfo // pro transponovaná data sérií
    vectorColumnIndices?: number[] // indexy sloupců, které obsahují vektorová data
}

/**
 * informace o horizontálních (transponovaných) sériích.
 * používá se, když jsou hodnoty osy x v řádku (např. vlnová délka 230, 232, 234...)
 * a následuje více řádků hodnot y, seskupených podle popisků.
 */
export interface HorizontalSeriesInfo {
    xAxisRow: number // který řádek obsahuje hodnoty x (relativně k začátku bloku)
    xAxisLabel: string // popisek pro osu x (např. „vlnová délka“, „čas“)
    xValues: number[] // zparsované hodnoty x
    groups: HorizontalSeriesGroup[] // skupiny hodnot y
}

export interface HorizontalSeriesGroup {
    label: string // popisek skupiny (např. „k2“, „(kr sln)“, „sln“)
    startRow: number // počáteční řádek relativně k bloku
    rowCount: number // počet řádků hodnot y v této skupině
}

export type BlockAction = 'main_table' | 'metadata' | 'series' | 'ignore'

// ============ původ pole (provenance) ============

export interface FieldProvenance {
    blockId: string
    kind: 'table_column' | 'kv_key' | 'series'
    columnIndex?: number
    key?: string
    autoGenerated: boolean
}

// ============ návrh parsování (proposal) ============

export interface ParseProposal {
    blocks: DetectedBlock[]
    suggestedMainBlock: string | null // id doporučeného bloku
    rawKind: 'text' | 'grid'
    rawLines?: string[] // pro csv/tsv/txt
    rawGrid?: string[][] // pro xlsx
}

// ============ profily předvoleb (presets) ============

export interface ImportPreset {
    id: string
    name: string
    delimiter: ',' | ';' | '\t' | '|' | 'auto'
    decimal: '.' | ',' | 'auto'
    header: 'auto' | 'no_header' | number
    skipEmptyLines: boolean
}

export const IMPORT_PRESETS: ImportPreset[] = [
    {
        id: 'csv_standard',
        name: 'CSV Standard (,)',
        delimiter: ',',
        decimal: '.',
        header: 'auto',
        skipEmptyLines: true
    },
    {
        id: 'csv_eu',
        name: 'EU CSV (;)',
        delimiter: ';',
        decimal: ',',
        header: 'auto',
        skipEmptyLines: true
    },
    {
        id: 'tsv',
        name: 'TSV / Tab',
        delimiter: '\t',
        decimal: '.',
        header: 'auto',
        skipEmptyLines: true
    },
    {
        id: 'excel',
        name: 'Excel (TAB, auto)',
        delimiter: '\t',
        decimal: 'auto',
        header: 'auto',
        skipEmptyLines: true
    },
    {
        id: 'auto',
        name: 'Automaticky',
        delimiter: 'auto',
        decimal: 'auto',
        header: 'auto',
        skipEmptyLines: true
    }
]

// ============ pomocné funkce ============

export function generateBlockId(): string {
    return 'blk_' + Math.random().toString(36).slice(2, 10)
}

export function getBlockTypeLabel(type: BlockType): string {
    switch (type) {
        case 'kv': return 'Key-Value'
        case 'table': return 'Tabulka'
        case 'series': return 'Datová série'
        case 'stats': return 'Statistiky'
        case 'unknown': return 'Neznámé'
    }
}

export function getBlockActionLabel(action: BlockAction): string {
    switch (action) {
        case 'main_table': return 'Hlavní tabulka'
        case 'metadata': return 'Metadata'
        case 'series': return 'Série'
        case 'ignore': return 'Ignorováno'
    }
}
