/**
 * Types for the three-layer import architecture.
 * Layer 1: Raw Data (untouched)
 * Layer 2: Parser Proposals (multiple blocks)
 * Layer 3: Template (user authority)
 */

// ============ BLOCK TYPES ============

export type BlockType = 'kv' | 'table' | 'series' | 'stats' | 'unknown'

export interface DetectedBlock {
    id: string
    type: BlockType
    startRow: number
    endRow: number
    columnCount?: number
    confidence: number // 0-1
    description: string
    headers?: string[]
    sampleRows?: string[][]
    selected?: boolean // User selected this block
    action?: BlockAction // What to do with this block
    horizontalSeries?: HorizontalSeriesInfo // For transposed series data
    vectorColumnIndices?: number[] // Column indices that contain vector data
}

/**
 * Horizontal (transposed) series info.
 * Used when X-axis values are in a row (e.g., wavelength 230, 232, 234...)
 * and multiple Y-value rows follow, grouped by labels.
 */
export interface HorizontalSeriesInfo {
    xAxisRow: number // Which row contains X values (relative to block start)
    xAxisLabel: string // Label for X axis (e.g., "Wavel.", "Time")
    xValues: number[] // Parsed X values
    groups: HorizontalSeriesGroup[] // Y-value groups
}

export interface HorizontalSeriesGroup {
    label: string // Group label (e.g., "K2", "(KR SLN)", "SLN")
    startRow: number // Start row relative to block
    rowCount: number // Number of Y-value rows in this group
}

export type BlockAction = 'main_table' | 'metadata' | 'series' | 'ignore'

// ============ FIELD PROVENANCE ============

export interface FieldProvenance {
    blockId: string
    kind: 'table_column' | 'kv_key' | 'series'
    columnIndex?: number
    key?: string
    autoGenerated: boolean
}

// ============ PARSE PROPOSAL ============

export interface ParseProposal {
    blocks: DetectedBlock[]
    suggestedMainBlock: string | null // id of recommended block
    rawKind: 'text' | 'grid'
    rawLines?: string[] // For CSV/TSV/TXT
    rawGrid?: string[][] // For XLSX
}

// ============ PRESET PROFILES ============

export interface ImportPreset {
    id: string
    name: string
    delimiter: ',' | ';' | '\t' | '|' | 'auto'
    decimal: '.' | ',' | 'auto'
    header: 'auto' | 'no_header' | number
    skipEmptyLines: boolean
}

export const IMPORT_PRESETS: ImportPreset[] = [
    {
        id: 'csv_standard',
        name: 'CSV Standard (,)',
        delimiter: ',',
        decimal: '.',
        header: 'auto',
        skipEmptyLines: true
    },
    {
        id: 'csv_eu',
        name: 'EU CSV (;)',
        delimiter: ';',
        decimal: ',',
        header: 'auto',
        skipEmptyLines: true
    },
    {
        id: 'tsv',
        name: 'TSV / Tab',
        delimiter: '\t',
        decimal: '.',
        header: 'auto',
        skipEmptyLines: true
    },
    {
        id: 'excel',
        name: 'Excel (TAB, auto)',
        delimiter: '\t',
        decimal: 'auto',
        header: 'auto',
        skipEmptyLines: true
    },
    {
        id: 'auto',
        name: 'Automaticky',
        delimiter: 'auto',
        decimal: 'auto',
        header: 'auto',
        skipEmptyLines: true
    }
]

// ============ HELPER FUNCTIONS ============

export function generateBlockId(): string {
    return 'blk_' + Math.random().toString(36).slice(2, 10)
}

export function getBlockTypeLabel(type: BlockType): string {
    switch (type) {
        case 'kv': return 'Key-Value'
        case 'table': return 'Tabulka'
        case 'series': return 'Datová série'
        case 'stats': return 'Statistiky'
        case 'unknown': return 'Neznámé'
    }
}

export function getBlockActionLabel(action: BlockAction): string {
    switch (action) {
        case 'main_table': return 'Hlavní tabulka'
        case 'metadata': return 'Metadata'
        case 'series': return 'Série'
        case 'ignore': return 'Ignorováno'
    }
}
