/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppPrimaryButton: typeof import('./components/ui/AppPrimaryButton.vue')['default']
    AppToolbar: typeof import('./components/AppToolbar.vue')['default']
    BarChart: typeof import('./components/sumarry/BarChart.vue')['default']
    BoardListContent: typeof import('./components/board/BoardListContent.vue')['default']
    BoardLists: typeof import('./components/board/BoardLists.vue')['default']
    CommentRow: typeof import('./components/board/card/CommentRow.vue')['default']
    DailyListView: typeof import('./components/reservations/DailyListView.vue')['default']
    DailyMachinesView: typeof import('./components/reservations/DailyMachinesView.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    EntityEditorDialog: typeof import('./components/EntityEditorDialog.vue')['default']
    EventDetailCard: typeof import('./components/reservations/EventDetailCard.vue')['default']
    ChartPanel: typeof import('./components/measurement/ChartPanel.vue')['default']
    ChartStats: typeof import('./components/chart/ChartStats.vue')['default']
    ChartVisualizer: typeof import('./components/chart/ChartVisualizer.vue')['default']
    LeftFiltersPanel: typeof import('./components/LeftFiltersPanel.vue')['default']
    LeftNavigation: typeof import('./components/LeftNavigation.vue')['default']
    MeasurementCreateDialog: typeof import('./components/measurement/MeasurementCreateDialog.vue')['default']
    MeasurementDetailDialog: typeof import('./components/measurement/MeasurementDetailDialog.vue')['default']
    MeasurementCharts: typeof import('./components/measurement/MeasurementCharts.vue')['default']
    MeasurementTable: typeof import('./components/measurement/MeasurementTable.vue')['default']
    OpenedCard: typeof import('./components/board/card/OpenedCard.vue')['default']
    PickedBlocksEditor: typeof import('./components/import/PickedBlocksEditor.vue')['default']
    ProjectForm: typeof import('./components/project/ProjectForm.vue')['default']
    RepeatSetControls: typeof import('./components/import/RepeatSetControls.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideFilter: typeof import('./components/board/sideFilter/SideFilter.vue')['default']
    SideFilterRow: typeof import('./components/board/sideFilter/SideFilterRow.vue')['default']
    TemplateFromClipboardDialog: typeof import('./components/import/TemplateFromClipboardDialog.vue')['default']
    TemplateFromClipboardDialog3: typeof import('./components/import/TemplateFromClipboardDialog3.vue')['default']
    TemplatesOverviewDialog: typeof import('./components/measurement/TemplatesOverviewDialog.vue')['default']
    TemplateWizardDialog: typeof import('./components/import/TemplateWizardDialog.vue')['default']
    TimePicker: typeof import('./components/TimePicker.vue')['default']
    Timer: typeof import('./components/board/card/Timer.vue')['default']
    TimeRecordForm: typeof import('./components/board/card/TimeRecordForm.vue')['default']
    TimerTable: typeof import('./components/board/card/TimerTable.vue')['default']
    WeekView: typeof import('./components/reservations/WeekView.vue')['default']
  }
}
