/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppToolbar: typeof import('./components/AppToolbar.vue')['default']
    BarChart: typeof import('./components/sumarry/BarChart.vue')['default']
    BoardListContent: typeof import('./components/board/BoardListContent.vue')['default']
    BoardLists: typeof import('./components/board/BoardLists.vue')['default']
    CommentRow: typeof import('./components/board/card/CommentRow.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    LeftNavigation: typeof import('./components/LeftNavigation.vue')['default']
    MeasurementForm: typeof import('./components/board/measurement/MeasurementForm.vue')['default']
    OpenedCard: typeof import('./components/board/card/OpenedCard.vue')['default']
    ProjectForm: typeof import('./components/project/ProjectForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideFilter: typeof import('./components/board/sideFilter/SideFilter.vue')['default']
    SideFilterRow: typeof import('./components/board/sideFilter/SideFilterRow.vue')['default']
    TimePicker: typeof import('./components/TimePicker.vue')['default']
    Timer: typeof import('./components/board/card/Timer.vue')['default']
    TimeRecordForm: typeof import('./components/board/card/TimeRecordForm.vue')['default']
    TimerTable: typeof import('./components/board/card/TimerTable.vue')['default']
  }
}
