/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AuthSection': RouteRecordInfo<'/AuthSection', '/AuthSection', Record<never, never>, Record<never, never>>,
    '/Board': RouteRecordInfo<'/Board', '/Board', Record<never, never>, Record<never, never>>,
    '/LoggedOut': RouteRecordInfo<'/LoggedOut', '/LoggedOut', Record<never, never>, Record<never, never>>,
    '/Measurements': RouteRecordInfo<'/Measurements', '/Measurements', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/PeopleWork': RouteRecordInfo<'/PeopleWork', '/PeopleWork', Record<never, never>, Record<never, never>>,
    '/Project': RouteRecordInfo<'/Project', '/Project', Record<never, never>, Record<never, never>>,
    '/ProjectDetail': RouteRecordInfo<'/ProjectDetail', '/ProjectDetail', Record<never, never>, Record<never, never>>,
    '/Reservations': RouteRecordInfo<'/Reservations', '/Reservations', Record<never, never>, Record<never, never>>,
    '/Summary': RouteRecordInfo<'/Summary', '/Summary', Record<never, never>, Record<never, never>>,
  }
}
